
//
// Copyright (c) 2014 Limit Point Systems, Inc. 
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

//
//
// Common SWIG interface to sheaves cluster
//
//=============================================================================

//$$SCRIBBLE: This file contains only the part of the Swig interface which
//            is to be inserted directly into the generated code.
//            We have to break the interface into two parts because
//            of the way Swig handles "%import" versus "%include".
//            If you change this file make sure you also change
//            "sheaves_common_binding.i" as well.

//=============================================================================

%{

#include "std_string.h"

#include "ComLimitPoint/sheaf/sheaf_dll_spec.h"
#include "ComLimitPoint/sheaf/sheaf.h"
#include "ComLimitPoint/sheaf/poset_type.h"
#include "ComLimitPoint/sheaf/pod_types.h"
#include "ComLimitPoint/sheaf/primitive_attributes.h"
#include "ComLimitPoint/sheaf/primitive_value.h"
#include "ComLimitPoint/sheaf/primitive_type.h"
#include "ComLimitPoint/sheaf/standard_dof_tuple_index.h"
#include "ComLimitPoint/sheaf/standard_member_index.h"
#include "ComLimitPoint/sheaf/standard_subposet_index.h"
#include "ComLimitPoint/sheaf/standard_version_index.h"
#include "ComLimitPoint/sheaf/dof_tuple_type.h"
#include "ComLimitPoint/sheaf/namespace_relative_member_index.h"
#include "ComLimitPoint/sheaf/namespace_relative_subposet_index.h"
#include "ComLimitPoint/sheaf/rc_ptr.h"

#include "ComLimitPoint/sheaf/any.h"
#include       "ComLimitPoint/sheaf/abstract_product_structure.h"
#include             "ComLimitPoint/sheaf/ij_product_structure.h"
#include             "ComLimitPoint/sheaf/ijk_product_structure.h"
#include       "ComLimitPoint/sheaf/data_converter.h"
#include       "ComLimitPoint/sheaf/data_type_map.h"
#include             "ComLimitPoint/sheaf/file_data_type_map.h"
#include             "ComLimitPoint/sheaf/poset_data_type_map.h"
#include       "ComLimitPoint/sheaf/depth_first_iterator.h"
#include             "ComLimitPoint/sheaf/filtered_depth_first_iterator.h"
#include                   "ComLimitPoint/sheaf/biorder_iterator.h"
#include                   "ComLimitPoint/sheaf/linkorder_iterator.h"
#include                   "ComLimitPoint/sheaf/postorder_iterator.h"
#include                   "ComLimitPoint/sheaf/preorder_iterator.h"
#include                   "ComLimitPoint/sheaf/triorder_iterator.h"
#include       "ComLimitPoint/sheaf/depth_first_itr.h"
#include             "ComLimitPoint/sheaf/filtered_depth_first_itr.h"
#include                   "ComLimitPoint/sheaf/biorder_itr.h"
#include                   "ComLimitPoint/sheaf/linkorder_itr.h"
#include                   "ComLimitPoint/sheaf/postorder_itr.h"
#include                   "ComLimitPoint/sheaf/preorder_itr.h"
#include                   "ComLimitPoint/sheaf/triorder_itr.h"
#include       "ComLimitPoint/sheaf/error_message.h"
#include       "ComLimitPoint/sheaf/filtered_depth_first_member_iterator.h"
#include             "ComLimitPoint/sheaf/postorder_member_iterator.h"
#include             "ComLimitPoint/sheaf/preorder_member_iterator.h"
#include       "ComLimitPoint/sheaf/index_equivalence_class.h"
#include       "ComLimitPoint/sheaf/index_equivalence_iterator.h"
#include       "ComLimitPoint/sheaf/index_space_collection.h"
#include             "ComLimitPoint/sheaf/explicit_index_space_collection.h"
#include             "ComLimitPoint/sheaf/index_space_interval.h"
#include                   "ComLimitPoint/sheaf/array_index_space_interval.h"
#include                   "ComLimitPoint/sheaf/explicit_index_space_interval.h"
#include                   "ComLimitPoint/sheaf/ragged_array_index_space_interval.h"
#include                   "ComLimitPoint/sheaf/singleton_index_space_interval.h"
#include       "ComLimitPoint/sheaf/index_space_family.h"
#include       "ComLimitPoint/sheaf/index_space_family_iterator.h"
#include       "ComLimitPoint/sheaf/index_space_handle.h"
#include             "ComLimitPoint/sheaf/forwarding_index_space_handle.h"
#include             "ComLimitPoint/sheaf/explicit_index_space_handle.h"
#include                   "ComLimitPoint/sheaf/offset_index_space_handle.h"
#include                   "ComLimitPoint/sheaf/sum_index_space_handle.h"
#include                         "ComLimitPoint/sheaf/hub_index_space_handle.h"
#include                   "ComLimitPoint/sheaf/mutable_index_space_handle.h"
#include                         "ComLimitPoint/sheaf/array_index_space_handle.h"
#include                         "ComLimitPoint/sheaf/hash_index_space_handle.h"
#include                         "ComLimitPoint/sheaf/interval_index_space_handle.h"
#include                         "ComLimitPoint/sheaf/list_index_space_handle.h"
#include                   "ComLimitPoint/sheaf/primary_index_space_handle.h"
#include                         "ComLimitPoint/sheaf/reserved_primary_index_space_handle.h"
#include                   "ComLimitPoint/sheaf/primitives_index_space_handle.h"
#include                   "ComLimitPoint/sheaf/singleton_index_space_handle.h"
#include       "ComLimitPoint/sheaf/explicit_index_space_state.h"
#include             "ComLimitPoint/sheaf/offset_index_space_state.h"
#include             "ComLimitPoint/sheaf/mutable_index_space_state.h"
#include                   "ComLimitPoint/sheaf/array_index_space_state.h"
#include                   "ComLimitPoint/sheaf/hash_index_space_state.h"
#include                   "ComLimitPoint/sheaf/interval_index_space_state.h"
#include                   "ComLimitPoint/sheaf/list_index_space_state.h"
#include             "ComLimitPoint/sheaf/primary_index_space_state.h"
#include                   "ComLimitPoint/sheaf/reserved_primary_index_space_state.h"
#include             "ComLimitPoint/sheaf/sum_index_space_state.h"
#include                   "ComLimitPoint/sheaf/primary_sum_index_space_state.h"
#include             "ComLimitPoint/sheaf/primitives_index_space_state.h"
#include             "ComLimitPoint/sheaf/singleton_index_space_state.h"
#include       "ComLimitPoint/sheaf/index_space_interval_iterator.h"
#include       "ComLimitPoint/sheaf/index_space_iterator.h"
#include             "ComLimitPoint/sheaf/explicit_index_space_iterator.h"
#include                   "ComLimitPoint/sheaf/array_index_space_iterator.h"
#include                   "ComLimitPoint/sheaf/hash_index_space_iterator.h"
#include                   "ComLimitPoint/sheaf/hub_index_space_iterator.h"
#include                   "ComLimitPoint/sheaf/interval_index_space_iterator.h"
#include                   "ComLimitPoint/sheaf/list_index_space_iterator.h"
#include                   "ComLimitPoint/sheaf/offset_index_space_iterator.h"
#include                   "ComLimitPoint/sheaf/primary_index_space_iterator.h"
#include                   "ComLimitPoint/sheaf/primitives_index_space_iterator.h"
#include                   "ComLimitPoint/sheaf/reserved_primary_index_space_iterator.h"
#include                   "ComLimitPoint/sheaf/singleton_index_space_iterator.h"
#include             "ComLimitPoint/sheaf/implicit_index_space_iterator.h"
#include                   "ComLimitPoint/sheaf/array_implicit_index_space_iterator.h"
#include                   "ComLimitPoint/sheaf/constant_implicit_index_space_iterator.h"
#include                   "ComLimitPoint/sheaf/ragged_array_implicit_index_space_iterator.h"
#include                   "ComLimitPoint/sheaf/singleton_implicit_index_space_iterator.h"
#include "ComLimitPoint/sheaf/name_multimap.h"
#include "ComLimitPoint/sheaf/poset_bounds.h"
#include "ComLimitPoint/sheaf/poset_bounds_descriptor.h"
#include "ComLimitPoint/sheaf/poset_crg_state.h"
#include "ComLimitPoint/sheaf/poset_dof_iterator.h"
#include "ComLimitPoint/sheaf/poset_dof_map.h"
#include             "ComLimitPoint/sheaf/array_poset_dof_map.h"
#include             "ComLimitPoint/sheaf/namespace_poset_dof_map.h"
#include             "ComLimitPoint/sheaf/primitives_poset_dof_map.h"
#include "ComLimitPoint/sheaf/poset_joiner.h"
#include "ComLimitPoint/sheaf/poset_powerset_state.h"
#include "ComLimitPoint/sheaf/poset_scaffold.h"
#include "ComLimitPoint/sheaf/poset_table_state.h"
#include "ComLimitPoint/sheaf/poset_traverser.h"
#include                   "ComLimitPoint/sheaf/poset_orderer.h"
#include                   "ComLimitPoint/sheaf/poset_slicer.h"
#include "ComLimitPoint/sheaf/rc_any.h"
#include             "ComLimitPoint/sheaf/ragged_array.h"
#include "ComLimitPoint/sheaf/read_write_monitor.h"
#include             "ComLimitPoint/sheaf/poset_state.h"
#include "ComLimitPoint/sheaf/read_write_monitor_handle.h"
#include             "ComLimitPoint/sheaf/poset_component.h"
#include                   "ComLimitPoint/sheaf/abstract_poset_member.h"
#include                         "ComLimitPoint/sheaf/partial_poset_member.h"
#include                               "ComLimitPoint/sheaf/poset_member.h"
#include                         "ComLimitPoint/sheaf/total_poset_member.h"
#include                               "ComLimitPoint/sheaf/namespace_poset_member.h"
#include                               "ComLimitPoint/sheaf/poset_member_iterator.h"
//#include                                     "ComLimitPoint/sheaf/filtered_iterator.h"
#include                                     "ComLimitPoint/sheaf/subposet_member_iterator.h"
#include                               "ComLimitPoint/sheaf/schema_poset_member.h"
#include                   "ComLimitPoint/sheaf/subposet.h"
#include             "ComLimitPoint/sheaf/poset_state_handle.h"
#include                   "ComLimitPoint/sheaf/namespace_poset.h"
#include                         "ComLimitPoint/sheaf/sheaf_namespace.h"
#include                   "ComLimitPoint/sheaf/namespace_poset_schema.h"
#include                   "ComLimitPoint/sheaf/poset.h"
#include                         "ComLimitPoint/sheaf/refinable_poset.h"
#include                   "ComLimitPoint/sheaf/primitives_poset.h"
#include                   "ComLimitPoint/sheaf/primitives_poset_schema.h"
#include "ComLimitPoint/sheaf/record.h"
#include             "ComLimitPoint/sheaf/variable_length_record.h"
#include                   "ComLimitPoint/sheaf/attributes_record.h"
#include                         "ComLimitPoint/sheaf/dof_tuple_class_names_record.h"
#include                         "ComLimitPoint/sheaf/dof_tuple_col_bounds_record.h"
#include                         "ComLimitPoint/sheaf/dof_tuple_domain_offsets_record.h"
#include                         "ComLimitPoint/sheaf/dof_tuple_schema_ids_record.h"
#include                         "ComLimitPoint/sheaf/dof_tuple_schema_versions_record.h"
#include                         "ComLimitPoint/sheaf/dof_tuple_types_record.h"
#include                         "ComLimitPoint/sheaf/id_space_names_record.h"
#include                         "ComLimitPoint/sheaf/member_names_record.h"
#include                         "ComLimitPoint/sheaf/poset_general_record.h"
#include                         "ComLimitPoint/sheaf/subposet_names_record.h"
#include                         "ComLimitPoint/sheaf/table_dof_tuple_record.h"
#include                   "ComLimitPoint/sheaf/member_record.h"
#include "ComLimitPoint/sheaf/record_queue.h"
#include "ComLimitPoint/sheaf/record_set.h"
#include             "ComLimitPoint/sheaf/attributes_record_set.h"
#include             "ComLimitPoint/sheaf/dof_tuple_record_set.h"
#include             "ComLimitPoint/sheaf/member_record_set.h"
#include "ComLimitPoint/sheaf/schema_descriptor.h"
#include "ComLimitPoint/sheaf/sheaf_file.h"
#include "ComLimitPoint/sheaf/storage_agent.h"
#include "ComLimitPoint/sheaf/arg_list.h"
#include "ComLimitPoint/sheaf/auto_block.h"
#include "ComLimitPoint/sheaf/block.h"
#include             "ComLimitPoint/sheaf/binary_index_block.h"
#include             "ComLimitPoint/sheaf/id_block.h"
#include             "ComLimitPoint/sheaf/wsv_block.h"
#include "ComLimitPoint/sheaf/dof_descriptor_array.h"
#include "ComLimitPoint/sheaf/dof_map_factory.h"
//#include "ComLimitPoint/sheaf/factory.h"
#include "ComLimitPoint/sheaf/index_iterator.h"
#include "ComLimitPoint/sheaf/int_set.h"
#include "ComLimitPoint/sheaf/plot.h"
#include "ComLimitPoint/sheaf/pool.h"
#include "ComLimitPoint/sheaf/poset_handle_factory.h"
#include "ComLimitPoint/sheaf/poset_path.h"
#include "ComLimitPoint/sheaf/ptr_linked_pool.h"
#include "ComLimitPoint/sheaf/record_map.h"
#include "ComLimitPoint/sheaf/runnable.h"
#include "ComLimitPoint/sheaf/scoped_index.h"
#include "ComLimitPoint/sheaf/stop_watch.h"
#include "ComLimitPoint/sheaf/subposet_state.h"
#include "ComLimitPoint/sheaf/tern.h"
#include "ComLimitPoint/sheaf/thread.h"
#include "ComLimitPoint/sheaf/thread_condition_variable.h"
#include "ComLimitPoint/sheaf/thread_mutex.h"
#include "ComLimitPoint/sheaf/zn_to_bool.h"

#include "ComLimitPoint/sheaf/deep_size.h"

using namespace std;
using namespace sheaf;

%}

