#! /bin/tcsh

if($#argv == 0) then
  echo "usage: time_scalable_hex_write <index upper bnound>"
  exit
endif

@ ub = $1
@ i = 1

while ($i <= $ub)
  @ iblck = $ub / $i
  @ j = 1
  while ($j <= $i)
    @ jblck = $ub / $j
    @ k = 1
    while ($k <= $j)
      @ kblck =  $ub / $k
      echo timeing scalable_partial_hex_write.t $i $j $k $iblck $jblck $kblck\: `time scalable_partial_hex_write.t $i $j $k $iblck $jblck $kblck`   
      @ k *= 2 
    end
    @ j *= 2
  end
  @ i *= 2
end
