
//
// Copyright (c) 2014 Limit Point Systems, Inc. 
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

//
// Common Swig interface for fiber_bundles cluster
//

//=============================================================================

//$$SCRIBBLE: This file contains only the part of the Swig interface which
//            is to be inserted directly into the generated code.
//            We have to break the interface into two parts because
//            of the way Swig handles "%import" versus "%include".
//            If you change this file make sure you also change
//            "fiber_bundles_common_binding.i" as well.

//=============================================================================

%{

#include "ComLimitPoint/fiber_bundle/fiber_bundle.h"

#include "ComLimitPoint/fiber_bundle/base_space_factory.h"
#include "ComLimitPoint/fiber_bundle/base_space_member.h"
#include       "ComLimitPoint/fiber_bundle/homogeneous_block.h"
#include             "ComLimitPoint/fiber_bundle/point_block_1d.h"
#include             "ComLimitPoint/fiber_bundle/point_block_2d.h"
#include             "ComLimitPoint/fiber_bundle/point_block_3d.h"
#include             "ComLimitPoint/fiber_bundle/structured_block.h"
#include                   "ComLimitPoint/fiber_bundle/structured_block_1d.h"
#include                   "ComLimitPoint/fiber_bundle/structured_block_2d.h"
#include                   "ComLimitPoint/fiber_bundle/structured_block_3d.h"
#include             "ComLimitPoint/fiber_bundle/unstructured_block.h"
#include       "ComLimitPoint/fiber_bundle/local_base_space_member.h"
#include "ComLimitPoint/fiber_bundle/base_space_poset.h"
#include "ComLimitPoint/fiber_bundle/binary_index.h"
#include "ComLimitPoint/fiber_bundle/binary_index_space.h"
#include "ComLimitPoint/fiber_bundle/block_connectivity.h"
#include       "ComLimitPoint/fiber_bundle/hex_connectivity.h"
#include       "ComLimitPoint/fiber_bundle/line_connectivity.h"
#include       "ComLimitPoint/fiber_bundle/point_connectivity.h"
#include       "ComLimitPoint/fiber_bundle/quad_connectivity.h"
#include       "ComLimitPoint/fiber_bundle/tetra_connectivity.h"
#include       "ComLimitPoint/fiber_bundle/triangle_connectivity.h"
#include "ComLimitPoint/fiber_bundle/chart_point.h"
#include       "ComLimitPoint/fiber_bundle/chart_point_1d.h"
#include       "ComLimitPoint/fiber_bundle/chart_point_2d.h"
#include       "ComLimitPoint/fiber_bundle/chart_point_3d.h"
#include "ComLimitPoint/fiber_bundle/discretization_context.h"
#include "ComLimitPoint/fiber_bundle/discretization_iterator.h"
#include "ComLimitPoint/fiber_bundle/eval_family.h"
#include       "ComLimitPoint/fiber_bundle/constant_eval_family.h"
#include       "ComLimitPoint/fiber_bundle/dlinear_eval_family.h"
#include       "ComLimitPoint/fiber_bundle/uniform_eval_family.h"
#include "ComLimitPoint/fiber_bundle/eval_iterator.h"
#include "ComLimitPoint/fiber_bundle/fiber_bundle_namespace.h"
#include "ComLimitPoint/fiber_bundle/group.h"
#include       "ComLimitPoint/fiber_bundle/gln.h"
#include             "ComLimitPoint/fiber_bundle/gl2.h"
#include             "ComLimitPoint/fiber_bundle/gl3.h"
#include "ComLimitPoint/fiber_bundle/gln_space.h"
#include "ComLimitPoint/fiber_bundle/i_adjacency_implicit_index_space_iterator.h"
#include "ComLimitPoint/fiber_bundle/i_adjacency_index_space_interval.h"
#include "ComLimitPoint/fiber_bundle/i_connectivity_implicit_index_space_iterator.h"
#include "ComLimitPoint/fiber_bundle/i_connectivity_index_space_interval.h"
#include "ComLimitPoint/fiber_bundle/ij_adjacency_implicit_index_space_iterator.h"
#include "ComLimitPoint/fiber_bundle/ij_adjacency_index_space_interval.h"
#include "ComLimitPoint/fiber_bundle/ij_connectivity_implicit_index_space_iterator.h"
#include "ComLimitPoint/fiber_bundle/ij_connectivity_index_space_interval.h"
#include "ComLimitPoint/fiber_bundle/ijk_adjacency_implicit_index_space_iterator.h"
#include "ComLimitPoint/fiber_bundle/ijk_adjacency_index_space_interval.h"
#include "ComLimitPoint/fiber_bundle/ijk_connectivity_implicit_index_space_iterator.h"
#include "ComLimitPoint/fiber_bundle/ijk_connectivity_index_space_interval.h"
#include "ComLimitPoint/fiber_bundle/sec_rep_descriptor.h"
#include "ComLimitPoint/fiber_bundle/sec_rep_space.h"
#include       "ComLimitPoint/fiber_bundle/sec_tuple_space.h"
#include             "ComLimitPoint/fiber_bundle/sec_vd_space.h"
#include                   "ComLimitPoint/fiber_bundle/sec_jcb_space.h"
#include                   "ComLimitPoint/fiber_bundle/sec_tp_space.h"
#include                         "ComLimitPoint/fiber_bundle/sec_atp_space.h"
#include                              "ComLimitPoint/fiber_bundle/sec_at0_space.h"
#include                              "ComLimitPoint/fiber_bundle/sec_at1_space.h"
#include                         "ComLimitPoint/fiber_bundle/sec_stp_space.h"
#include "ComLimitPoint/fiber_bundle/sec_rep_space_member.h"
#include       "ComLimitPoint/fiber_bundle/sec_tuple.h"
#include       "ComLimitPoint/fiber_bundle/sec_vd.h"
#include             "ComLimitPoint/fiber_bundle/sec_jcb.h"
#include                   "ComLimitPoint/fiber_bundle/sec_jcb_ed.h"
#include                         "ComLimitPoint/fiber_bundle/sec_jcb_e13.h"
#include                         "ComLimitPoint/fiber_bundle/sec_jcb_e23.h"
#include                         "ComLimitPoint/fiber_bundle/sec_jcb_e33.h"
#include             "ComLimitPoint/fiber_bundle/sec_tp.h"
#include                   "ComLimitPoint/fiber_bundle/sec_atp.h"
#include                         "ComLimitPoint/fiber_bundle/sec_at0.h"
#include                         "ComLimitPoint/fiber_bundle/sec_at1.h"
#include                               "ComLimitPoint/fiber_bundle/sec_ed.h"
#include                                     "ComLimitPoint/fiber_bundle/sec_e1.h"
#include                                           "ComLimitPoint/fiber_bundle/sec_e1_uniform.h"
#include                                     "ComLimitPoint/fiber_bundle/sec_e2.h"
#include                                           "ComLimitPoint/fiber_bundle/sec_e2_uniform.h"
#include                                     "ComLimitPoint/fiber_bundle/sec_e3.h"
#include                                           "ComLimitPoint/fiber_bundle/sec_e3_uniform.h"
#include                                     "ComLimitPoint/fiber_bundle/sec_e4.h"
#include                         "ComLimitPoint/fiber_bundle/sec_at2.h"
#include                               "ComLimitPoint/fiber_bundle/sec_at2_e2.h"
#include                               "ComLimitPoint/fiber_bundle/sec_at2_e3.h"
#include                         "ComLimitPoint/fiber_bundle/sec_at3.h"
#include                               "ComLimitPoint/fiber_bundle/sec_at3_e3.h"
#include                   "ComLimitPoint/fiber_bundle/sec_stp.h"
#include                         "ComLimitPoint/fiber_bundle/sec_st2.h"
#include                               "ComLimitPoint/fiber_bundle/sec_met.h"
#include                                     "ComLimitPoint/fiber_bundle/sec_met_ed.h"
#include                                           "ComLimitPoint/fiber_bundle/sec_met_e1.h"
#include                                           "ComLimitPoint/fiber_bundle/sec_met_e2.h"
#include                                           "ComLimitPoint/fiber_bundle/sec_met_e3.h"
#include                               "ComLimitPoint/fiber_bundle/sec_st2_e2.h"
#include                               "ComLimitPoint/fiber_bundle/sec_st2_e3.h"
#include                         "ComLimitPoint/fiber_bundle/sec_st3.h"
#include                               "ComLimitPoint/fiber_bundle/sec_st3_e3.h"
#include                         "ComLimitPoint/fiber_bundle/sec_st4.h"
#include                               "ComLimitPoint/fiber_bundle/sec_st4_e2.h"
#include                               "ComLimitPoint/fiber_bundle/sec_st4_e3.h"
#include                   "ComLimitPoint/fiber_bundle/sec_t2.h"
#include                         "ComLimitPoint/fiber_bundle/sec_t2_e2.h"
#include                         "ComLimitPoint/fiber_bundle/sec_t2_e3.h"
#include                   "ComLimitPoint/fiber_bundle/sec_t3.h"
#include                         "ComLimitPoint/fiber_bundle/sec_t3_e3.h"
#include                   "ComLimitPoint/fiber_bundle/sec_t4.h"
#include                         "ComLimitPoint/fiber_bundle/sec_t4_e2.h"
#include                         "ComLimitPoint/fiber_bundle/sec_t4_e3.h"
#include "ComLimitPoint/fiber_bundle/section_component_iterator.h"
#include       "ComLimitPoint/fiber_bundle/binary_section_component_iterator.h"
#include "ComLimitPoint/fiber_bundle/section_dof_iterator.h"
#include 	"ComLimitPoint/fiber_bundle/binary_section_dof_iterator.h"
#include "ComLimitPoint/fiber_bundle/section_dof_map.h"
#include        "ComLimitPoint/fiber_bundle/array_section_dof_map.h"
#include        "ComLimitPoint/fiber_bundle/sparse_section_dof_map.h"
#include "ComLimitPoint/fiber_bundle/section_eval_iterator.h"
#include "ComLimitPoint/fiber_bundle/section_evaluator.h"
#include       "ComLimitPoint/fiber_bundle/differentiable_section_evaluator.h"
#include       "ComLimitPoint/fiber_bundle/integrable_section_evaluator.h"
#include       "ComLimitPoint/fiber_bundle/linear_fcn_space.h"
#include             "ComLimitPoint/fiber_bundle/bilinear_2d.h"
#include             "ComLimitPoint/fiber_bundle/constant_fcn_space.h"
#include                   "ComLimitPoint/fiber_bundle/constant_hex.h"
#include                   "ComLimitPoint/fiber_bundle/constant_point.h"
#include                   "ComLimitPoint/fiber_bundle/constant_quad.h"
#include                   "ComLimitPoint/fiber_bundle/constant_segment.h"
#include                   "ComLimitPoint/fiber_bundle/constant_tet.h"
#include                   "ComLimitPoint/fiber_bundle/constant_triangle.h"
#include             "ComLimitPoint/fiber_bundle/linear_1d.h"
#include             "ComLimitPoint/fiber_bundle/linear_2d.h"
#include             "ComLimitPoint/fiber_bundle/linear_3d.h"
#include             "ComLimitPoint/fiber_bundle/quadratic_1d.h"
#include             "ComLimitPoint/fiber_bundle/quadratic_2d.h"
#include             "ComLimitPoint/fiber_bundle/quadratic_3d.h"
#include             "ComLimitPoint/fiber_bundle/trilinear_3d.h"
#include             "ComLimitPoint/fiber_bundle/uniform_1d.h"
#include             "ComLimitPoint/fiber_bundle/uniform_2d.h"
#include             "ComLimitPoint/fiber_bundle/uniform_3d.h"
#include "ComLimitPoint/fiber_bundle/section_iteration_state.h"
#include "ComLimitPoint/fiber_bundle/section_space_schema_jims_index_space_handle.h"
#include "ComLimitPoint/fiber_bundle/section_space_schema_jims_index_space_iterator.h"
#include "ComLimitPoint/fiber_bundle/section_space_schema_jims_index_space_state.h"
#include "ComLimitPoint/fiber_bundle/section_space_schema_member.h"
#include       "ComLimitPoint/fiber_bundle/binary_section_space_schema_member.h"
#include "ComLimitPoint/fiber_bundle/section_space_schema_poset.h"
#include       "ComLimitPoint/fiber_bundle/binary_section_space_schema_poset.h"
#include "ComLimitPoint/fiber_bundle/ternary_index.h"
#include "ComLimitPoint/fiber_bundle/ternary_index_space.h"
#include "ComLimitPoint/fiber_bundle/tuple.h"
#include       "ComLimitPoint/fiber_bundle/vd.h"
#include             "ComLimitPoint/fiber_bundle/jcb.h"
#include                   "ComLimitPoint/fiber_bundle/jcb_ed.h"
#include                         "ComLimitPoint/fiber_bundle/jcb_e13.h"
#include                         "ComLimitPoint/fiber_bundle/jcb_e23.h"
#include                         "ComLimitPoint/fiber_bundle/jcb_e33.h"
#include             "ComLimitPoint/fiber_bundle/tp.h"
#include                   "ComLimitPoint/fiber_bundle/atp.h"
#include                         "ComLimitPoint/fiber_bundle/at0.h"
#include                         "ComLimitPoint/fiber_bundle/at1.h"
#include                               "ComLimitPoint/fiber_bundle/ed.h"
#include                                     "ComLimitPoint/fiber_bundle/e1.h"
#include                                     "ComLimitPoint/fiber_bundle/e2.h"
#include                                     "ComLimitPoint/fiber_bundle/e3.h"
#include                                     "ComLimitPoint/fiber_bundle/e4.h"
#include                         "ComLimitPoint/fiber_bundle/at2.h"
#include                               "ComLimitPoint/fiber_bundle/at2_e2.h"
#include                               "ComLimitPoint/fiber_bundle/at2_e3.h"
#include                         "ComLimitPoint/fiber_bundle/at3.h"
#include                               "ComLimitPoint/fiber_bundle/at3_e3.h"
#include                   "ComLimitPoint/fiber_bundle/stp.h"
#include                         "ComLimitPoint/fiber_bundle/st2.h"
#include                               "ComLimitPoint/fiber_bundle/met.h"
#include                                     "ComLimitPoint/fiber_bundle/met_ed.h"
#include                                           "ComLimitPoint/fiber_bundle/met_e1.h"
#include                                           "ComLimitPoint/fiber_bundle/met_e2.h"
#include                                           "ComLimitPoint/fiber_bundle/met_e3.h"
#include                               "ComLimitPoint/fiber_bundle/st2_e2.h"
#include                               "ComLimitPoint/fiber_bundle/st2_e3.h"
#include                         "ComLimitPoint/fiber_bundle/st3.h"
#include                               "ComLimitPoint/fiber_bundle/st3_e3.h"
#include                         "ComLimitPoint/fiber_bundle/st4.h"
#include                               "ComLimitPoint/fiber_bundle/st4_e2.h"
#include                               "ComLimitPoint/fiber_bundle/st4_e3.h"
#include                   "ComLimitPoint/fiber_bundle/t2.h"
#include                         "ComLimitPoint/fiber_bundle/t2_e2.h"
#include                         "ComLimitPoint/fiber_bundle/t2_e3.h"
#include                   "ComLimitPoint/fiber_bundle/t3.h"
#include                         "ComLimitPoint/fiber_bundle/t3_e3.h"
#include                   "ComLimitPoint/fiber_bundle/t4.h"
#include                         "ComLimitPoint/fiber_bundle/t4_e2.h"
#include                         "ComLimitPoint/fiber_bundle/t4_e3.h"
#include "ComLimitPoint/fiber_bundle/tuple_space.h"
#include       "ComLimitPoint/fiber_bundle/vd_space.h"
#include             "ComLimitPoint/fiber_bundle/jcb_space.h"
#include             "ComLimitPoint/fiber_bundle/tp_space.h"
#include                   "ComLimitPoint/fiber_bundle/atp_space.h"
#include                         "ComLimitPoint/fiber_bundle/at0_space.h"
#include                         "ComLimitPoint/fiber_bundle/at1_space.h"
#include                   "ComLimitPoint/fiber_bundle/stp_space.h"
#include "ComLimitPoint/fiber_bundle/unary_index_space.h"
#include "ComLimitPoint/fiber_bundle/unstructured_block_builder.h"

using namespace std;
using namespace fiber_bundle;

%}

//=============================================================================
