#! /bin/tcsh
#
# Copyright (c) 2013 Limit Point Systems, Inc. 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if($#argv == 0) then
  echo "usage: time_scalable_hex_write <index upper bnound>"
  exit
endif

@ ub = $1
@ i = 1

while ($i <= $ub)
  @ iblck = $ub / $i
  @ j = 1
  while ($j <= $i)
    @ jblck = $ub / $j
    @ k = 1
    while ($k <= $j)
      @ kblck =  $ub / $k
      echo timeing scalable_partial_hex_write.t $i $j $k $iblck $jblck $kblck\: `time scalable_partial_hex_write.t $i $j $k $iblck $jblck $kblck`   
      @ k *= 2 
    end
    @ j *= 2
  end
  @ i *= 2
end
